nioSocketServer:
  host : 127.0.0.1
  port : 9005

akkaRemoteActor:
  matchingPath: akka.tcp://MatchingWorkerSystem@127.0.0.1:2551/user/matchingRouter
  roomPath: akka.tcp://MatchingWorkerSystem@127.0.0.1:2552/user/matchingRouter