nioSocketServer:
  host : 127.0.0.1
  port : 9005

akkaRemoteActor:
  matchingRequestPath: nio_akka.tcp://MatchingWorkerSystem@127.0.0.1:2551/user/matchingRequestActor
  matchingNotifyPath: nio_akka.tcp://MatchingWorkerSystem@127.0.0.1:2551/user/matchingNotifyActor

  roomRequestPath: nio_akka.tcp://RoomWorkerSystem@127.0.0.1:2552/user/roomRequestActor
  roomServerRequestPath: nio_akka.tcp://RoomWorkerSystem@127.0.0.1:2552/user/roomServerRequestActor
  roomNotifyPath: nio_akka.tcp://RoomWorkerSystem@127.0.0.1:2552/user/roomNotifyActor