version: "3"
services:

  # 网关服务器
  com.commalina.math24.play.gateway:
      image: commelina/math24-play-gateway
      restart: always
      ports:
        # 外网端口
        - "9005:9005"
      links:
        - com.commalina.math24.play.match
        - com.commalina.math24.play.room

  # 游戏匹配
  com.commalina.math24.play.match:
      image: commelina/math24-play-match
      restart: always

  # 游戏房间逻辑
  com.commalina.math24.play.room:
        image: commelina/math24-play-room
        restart: always