// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_error_code.proto

package com.commelina.math24.play.gateway.proto;

public final class ErrorCodeProtos {
  private ErrorCodeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030gateway_error_code.proto\022\013def.gateway*" +
      "\316\001\n\nERROR_CODE\022\n\n\006SUCESS\020\000\022\024\n\020DOMAIN_NOT" +
      "_FOUND\020\001\022\034\n\030GATEWAY_API_UNAUTHORIZED\020\002\022\035" +
      "\n\031MATCHING_API_UNAUTHORIZED\020\003\022\031\n\025ROOM_AP" +
      "I_UNAUTHORIZED\020\004\022\033\n\027ROOM_API_IMPORT_ROOM" +
      "_ID\020\005\022\022\n\016ROOM_NOT_FOUND\020\006\022\025\n\021TOKEN_PARSE" +
      "_ERROR\020\007B<\n\'com.commelina.math24.play.ga" +
      "teway.protoB\017ErrorCodeProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
