// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_error_code.proto

package com.commelina.math24.play.gateway.proto;

/**
 * <pre>
 * 错误码定义
 * </pre>
 *
 * Protobuf enum {@code def.gateway.ERROR_CODE}
 */
public enum ERROR_CODE
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCESS = 0;</code>
   */
  SUCESS(0),
  /**
   * <pre>
   * 作用域不存在
   * </pre>
   *
   * <code>DOMAIN_NOT_FOUND = 1;</code>
   */
  DOMAIN_NOT_FOUND(1),
  /**
   * <pre>
   * 网关该接口必须登录才能访问
   * </pre>
   *
   * <code>GATEWAY_API_UNAUTHORIZED = 2;</code>
   */
  GATEWAY_API_UNAUTHORIZED(2),
  /**
   * <pre>
   * 匹配接口必须登录才能访问
   * </pre>
   *
   * <code>MATCHING_API_UNAUTHORIZED = 3;</code>
   */
  MATCHING_API_UNAUTHORIZED(3),
  /**
   * <pre>
   * 房间必须登录才能访问
   * </pre>
   *
   * <code>ROOM_API_UNAUTHORIZED = 4;</code>
   */
  ROOM_API_UNAUTHORIZED(4),
  /**
   * <pre>
   * 第一个参数必须是 room id
   * </pre>
   *
   * <code>ROOM_API_IMPORT_ROOM_ID = 5;</code>
   */
  ROOM_API_IMPORT_ROOM_ID(5),
  /**
   * <pre>
   * 房间不存在
   * </pre>
   *
   * <code>ROOM_NOT_FOUND = 6;</code>
   */
  ROOM_NOT_FOUND(6),
  /**
   * <pre>
   * token 转换错误
   * </pre>
   *
   * <code>TOKEN_PARSE_ERROR = 7;</code>
   */
  TOKEN_PARSE_ERROR(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCESS = 0;</code>
   */
  public static final int SUCESS_VALUE = 0;
  /**
   * <pre>
   * 作用域不存在
   * </pre>
   *
   * <code>DOMAIN_NOT_FOUND = 1;</code>
   */
  public static final int DOMAIN_NOT_FOUND_VALUE = 1;
  /**
   * <pre>
   * 网关该接口必须登录才能访问
   * </pre>
   *
   * <code>GATEWAY_API_UNAUTHORIZED = 2;</code>
   */
  public static final int GATEWAY_API_UNAUTHORIZED_VALUE = 2;
  /**
   * <pre>
   * 匹配接口必须登录才能访问
   * </pre>
   *
   * <code>MATCHING_API_UNAUTHORIZED = 3;</code>
   */
  public static final int MATCHING_API_UNAUTHORIZED_VALUE = 3;
  /**
   * <pre>
   * 房间必须登录才能访问
   * </pre>
   *
   * <code>ROOM_API_UNAUTHORIZED = 4;</code>
   */
  public static final int ROOM_API_UNAUTHORIZED_VALUE = 4;
  /**
   * <pre>
   * 第一个参数必须是 room id
   * </pre>
   *
   * <code>ROOM_API_IMPORT_ROOM_ID = 5;</code>
   */
  public static final int ROOM_API_IMPORT_ROOM_ID_VALUE = 5;
  /**
   * <pre>
   * 房间不存在
   * </pre>
   *
   * <code>ROOM_NOT_FOUND = 6;</code>
   */
  public static final int ROOM_NOT_FOUND_VALUE = 6;
  /**
   * <pre>
   * token 转换错误
   * </pre>
   *
   * <code>TOKEN_PARSE_ERROR = 7;</code>
   */
  public static final int TOKEN_PARSE_ERROR_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ERROR_CODE valueOf(int value) {
    return forNumber(value);
  }

  public static ERROR_CODE forNumber(int value) {
    switch (value) {
      case 0: return SUCESS;
      case 1: return DOMAIN_NOT_FOUND;
      case 2: return GATEWAY_API_UNAUTHORIZED;
      case 3: return MATCHING_API_UNAUTHORIZED;
      case 4: return ROOM_API_UNAUTHORIZED;
      case 5: return ROOM_API_IMPORT_ROOM_ID;
      case 6: return ROOM_NOT_FOUND;
      case 7: return TOKEN_PARSE_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ERROR_CODE>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ERROR_CODE> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ERROR_CODE>() {
          public ERROR_CODE findValueByNumber(int number) {
            return ERROR_CODE.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.commelina.math24.play.gateway.proto.ErrorCodeProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final ERROR_CODE[] VALUES = values();

  public static ERROR_CODE valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ERROR_CODE(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:def.gateway.ERROR_CODE)
}

