// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_request_code.proto

package com.commelina.math24.play.gateway.proto;

/**
 * <pre>
 * 接口列表
 * </pre>
 *
 * Protobuf enum {@code def.gateway.GATEWAY_METHODS}
 */
public enum GATEWAY_METHODS
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>PASSPORT_CONNECT = 0;</code>
   */
  PASSPORT_CONNECT(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>PASSPORT_CONNECT = 0;</code>
   */
  public static final int PASSPORT_CONNECT_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GATEWAY_METHODS valueOf(int value) {
    return forNumber(value);
  }

  public static GATEWAY_METHODS forNumber(int value) {
    switch (value) {
      case 0: return PASSPORT_CONNECT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GATEWAY_METHODS>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GATEWAY_METHODS> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GATEWAY_METHODS>() {
          public GATEWAY_METHODS findValueByNumber(int number) {
            return GATEWAY_METHODS.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.commelina.math24.play.gateway.proto.MethodProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final GATEWAY_METHODS[] VALUES = values();

  public static GATEWAY_METHODS valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GATEWAY_METHODS(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:def.gateway.GATEWAY_METHODS)
}

