// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matching_room_request_opcode.proto

package com.commelina.math24.matching_room.proto;

public interface CREATE_ROOM_REQUESTOrBuilder extends
    // @@protoc_insertion_point(interface_extends:def.matching_room.CREATE_ROOM_REQUEST)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 roomId = 1;</code>
   */
  long getRoomId();

  /**
   * <code>repeated uint64 userIds = 2;</code>
   */
  java.util.List<java.lang.Long> getUserIdsList();
  /**
   * <code>repeated uint64 userIds = 2;</code>
   */
  int getUserIdsCount();
  /**
   * <code>repeated uint64 userIds = 2;</code>
   */
  long getUserIds(int index);
}
