// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matching_room_request_opcode.proto

package com.commelina.math24.matching_room.proto;

/**
 * Protobuf enum {@code def.matching_room.MATCH_ROOM_REQUEST_OPCODE}
 */
public enum MATCH_ROOM_REQUEST_OPCODE
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATE_ROOM = 0;</code>
   */
  CREATE_ROOM(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE_ROOM = 0;</code>
   */
  public static final int CREATE_ROOM_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MATCH_ROOM_REQUEST_OPCODE valueOf(int value) {
    return forNumber(value);
  }

  public static MATCH_ROOM_REQUEST_OPCODE forNumber(int value) {
    switch (value) {
      case 0: return CREATE_ROOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MATCH_ROOM_REQUEST_OPCODE>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MATCH_ROOM_REQUEST_OPCODE> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MATCH_ROOM_REQUEST_OPCODE>() {
          public MATCH_ROOM_REQUEST_OPCODE findValueByNumber(int number) {
            return MATCH_ROOM_REQUEST_OPCODE.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.commelina.math24.matching_room.proto.OpcodeDef.getDescriptor().getEnumTypes().get(0);
  }

  private static final MATCH_ROOM_REQUEST_OPCODE[] VALUES = values();

  public static MATCH_ROOM_REQUEST_OPCODE valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MATCH_ROOM_REQUEST_OPCODE(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:def.matching_room.MATCH_ROOM_REQUEST_OPCODE)
}

