// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matching_room_error_code.proto

package com.commelina.math24.matching_room.proto;

/**
 * Protobuf enum {@code def.matching_room.MATCH_ROOM_ERROR_CODE}
 */
public enum MATCH_ROOM_ERROR_CODE
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 房间不存在
   * </pre>
   *
   * <code>EMPTYS = 0;</code>
   */
  EMPTYS(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 房间不存在
   * </pre>
   *
   * <code>EMPTYS = 0;</code>
   */
  public static final int EMPTYS_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MATCH_ROOM_ERROR_CODE valueOf(int value) {
    return forNumber(value);
  }

  public static MATCH_ROOM_ERROR_CODE forNumber(int value) {
    switch (value) {
      case 0: return EMPTYS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MATCH_ROOM_ERROR_CODE>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MATCH_ROOM_ERROR_CODE> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MATCH_ROOM_ERROR_CODE>() {
          public MATCH_ROOM_ERROR_CODE findValueByNumber(int number) {
            return MATCH_ROOM_ERROR_CODE.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.commelina.math24.matching_room.proto.ErrorCodeDef.getDescriptor().getEnumTypes().get(0);
  }

  private static final MATCH_ROOM_ERROR_CODE[] VALUES = values();

  public static MATCH_ROOM_ERROR_CODE valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MATCH_ROOM_ERROR_CODE(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:def.matching_room.MATCH_ROOM_ERROR_CODE)
}

