// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matching_room_request_opcode.proto

package com.commelina.math24.matching_room.proto;

public final class OpcodeDef {
  private OpcodeDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_def_matching_room_CREATE_ROOM_REQUEST_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_def_matching_room_CREATE_ROOM_REQUEST_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"matching_room_request_opcode.proto\022\021de" +
      "f.matching_room\"6\n\023CREATE_ROOM_REQUEST\022\016" +
      "\n\006roomId\030\001 \001(\004\022\017\n\007userIds\030\002 \003(\004*,\n\031MATCH" +
      "_ROOM_REQUEST_OPCODE\022\017\n\013CREATE_ROOM\020\000B7\n" +
      "(com.commelina.math24.matching_room.prot" +
      "oB\tOpcodeDefP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_def_matching_room_CREATE_ROOM_REQUEST_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_def_matching_room_CREATE_ROOM_REQUEST_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_def_matching_room_CREATE_ROOM_REQUEST_descriptor,
        new java.lang.String[] { "RoomId", "UserIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
